# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 16:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_no', models.IntegerField(primary_key=True, serialize=False)),
                ('product_image', models.ImageField(upload_to='img')),
                ('product_name', models.CharField(default='product name', max_length=250)),
                ('start_date', models.DateTimeField(blank=True)),
                ('end_date', models.DateTimeField(blank=True)),
                ('product_details', models.CharField(default='product details', max_length=2000)),
                ('location', models.CharField(default='location', max_length=250)),
                ('price', models.IntegerField(default=0)),
                ('tag', models.CharField(default='tag', max_length=250)),
                ('init_date', models.DateTimeField(default=datetime.datetime(2017, 9, 30, 16, 27, 34, 114436))),
                ('seller_username', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
