# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20170926_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
