# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 17:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_product_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tag',
        ),
    ]
