# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 15:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20170926_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='date',
        ),
        migrations.AddField(
            model_name='product',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='product',
            name='location',
            field=models.CharField(default='location', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_details',
            field=models.CharField(default='product details', max_length=2000),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(default='product name', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(default='product type', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller_username',
            field=models.CharField(default='seller username', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='tag',
            field=models.CharField(default='tag', max_length=250),
        ),
    ]
