# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20170926_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(blank=True, upload_to='upload/image'),
        ),
    ]
