# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='post/upload/image/blank.png', upload_to='post/upload/image'),
        ),
    ]
