# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 08:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20170927_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='static/img/bank.jpg', upload_to=None),
        ),
    ]
