# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='post/static/img/bank.jpg', upload_to='post/static/img/product_image/'),
        ),
    ]
