# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20170927_0641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_username',
            field=models.CharField(default='seller_username', max_length=250),
        ),
    ]
