# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20170927_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='post/upload/image'),
        ),
    ]
