# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 18:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_auto_20170927_1701'),
        ('post', '0011_auto_20170927_1622'),
    ]

    operations = [
    ]
