# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_auto_20170927_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
