# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 08:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_auto_20170930_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller_username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
