# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 16:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_auto_20170930_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='init_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 30, 16, 0, 20, 418478)),
        ),
    ]
