# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 18:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20170930_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='init_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 1, 1, 9, 17, 70724)),
        ),
    ]
