# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_no', models.IntegerField(primary_key=True, serialize=False)),
                ('seller_username', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=250)),
                ('product_type', models.CharField(max_length=250)),
                ('product_details', models.CharField(max_length=2000)),
                ('date', models.DateField()),
                ('price', models.IntegerField()),
                ('tag', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
