# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 16:27
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True, max_length=500)),
                ('birthday', models.DateField(default=datetime.date.today)),
                ('bankaccount', models.CharField(blank=True, max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='userImage')),
            ],
        ),
    ]
