# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 17:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupLogin', '0002_auto_20170927_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
