# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupLogin', '0003_auto_20170927_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bankaccount',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='userImage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
